import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.75.0";
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Schema for the incoming payload generated by the AI assistant
const requestSchema = z.object({
  action: z.literal('create_time_block'),
  title: z.string().min(1).max(200),
  startTime: z.string(), // datetime or HH:MM / HH:MM:SS
  endTime: z.string(),   // datetime or HH:MM / HH:MM:SS
  category: z.string().max(50).optional(),
  taskIds: z.array(z.string()).optional(),
  dayOfWeek: z.number().min(0).max(6).optional(),
});

function toHHMMSS(time: string): { time: string; dayOfWeek: number | null } {
  // Returns normalized HH:MM:SS and best-effort dayOfWeek when a full datetime is provided
  try {
    if (time.includes('T') || time.includes(' ')) {
      const d = new Date(time);
      if (isNaN(d.getTime())) throw new Error('Invalid datetime');
      const hh = String(d.getHours()).padStart(2, '0');
      const mm = String(d.getMinutes()).padStart(2, '0');
      const ss = String(d.getSeconds()).padStart(2, '0');
      return { time: `${hh}:${mm}:${ss}`, dayOfWeek: d.getDay() };
    }

    // Assume HH:MM or HH:MM:SS
    const parts = time.split(':');
    if (parts.length < 2 || parts.length > 3) throw new Error('Invalid time');
    const hh = String(Number(parts[0])).padStart(2, '0');
    const mm = String(Number(parts[1])).padStart(2, '0');
    const ss = String(parts[2] ? Number(parts[2]) : 0).padStart(2, '0');
    return { time: `${hh}:${mm}:${ss}`, dayOfWeek: null };
  } catch (_e) {
    // If parsing fails, let caller handle
    throw new Error(`Invalid time format: ${time}`);
  }
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const requestId = crypto.randomUUID();
  const url = new URL(req.url);
  console.log(`[manage-time-blocks] (${requestId}) ${req.method} ${url.pathname}`);

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const anonKey = Deno.env.get('SUPABASE_ANON_KEY');
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!supabaseUrl || !anonKey || !serviceRoleKey) {
      console.error(`[${requestId}] Missing required environment variables`, {
        hasUrl: !!supabaseUrl,
        hasAnon: !!anonKey,
        hasService: !!serviceRoleKey,
      });
      return new Response(
        JSON.stringify({ success: false, error: 'Server misconfiguration' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }

    // Create an auth client using anon key to read the user from the Authorization header
    const authHeader = req.headers.get('Authorization') ?? '';
    const authClient = createClient(supabaseUrl, anonKey, {
      global: { headers: authHeader ? { Authorization: authHeader } : {} },
    });

    // Admin client (service role) used for DB writes (bypasses RLS safely within backend)
    const adminClient = createClient(supabaseUrl, serviceRoleKey);

    // Parse body
    let rawBody: unknown;
    try {
      rawBody = await req.json();
    } catch (e) {
      console.error(`[${requestId}] Failed to parse JSON body`, e);
      return new Response(
        JSON.stringify({ success: false, error: 'Invalid JSON body' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }

    console.log(`[${requestId}] Received body: ${JSON.stringify(rawBody)}`);

    // Validate
    const payload = requestSchema.parse(rawBody);

    // Authenticate user (required to associate the time block)
    const { data: userData, error: userError } = await authClient.auth.getUser();
    if (userError || !userData?.user) {
      console.error(`[${requestId}] Authentication failed`, userError);
      return new Response(
        JSON.stringify({ success: false, error: 'Unauthorized' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 401 }
      );
    }
    const userId = userData.user.id;
    console.log(`[${requestId}] Authenticated user: ${userId}`);

    // Normalize times and compute dayOfWeek
    const start = toHHMMSS(payload.startTime);
    const end = toHHMMSS(payload.endTime);
    const dayOfWeek = payload.dayOfWeek ?? start.dayOfWeek ?? new Date().getDay();

    console.log(`[${requestId}] Normalized times`, { start: start.time, end: end.time, dayOfWeek });

    // Optional: sanity check that end > start within a day
    const toMinutes = (t: string) => {
      const [h, m, s] = t.split(':').map((n) => Number(n));
      return h * 60 + m + (s > 0 ? 0.01 : 0); // tiny epsilon if seconds present
    };
    if (toMinutes(end.time) <= toMinutes(start.time)) {
      console.warn(`[${requestId}] endTime is not after startTime`);
    }

    // Insert into recurring_time_blocks (timeline-like recurring block)
    const insertPayload = {
      user_id: userId,
      title: payload.title,
      day_of_week: dayOfWeek,
      start_time: start.time,
      end_time: end.time,
      category: payload.category ?? 'other',
    } as const;

    const { data: timeBlock, error: insertError } = await adminClient
      .from('recurring_time_blocks')
      .insert(insertPayload)
      .select()
      .maybeSingle();

    if (insertError) {
      console.error(`[${requestId}] Insert failed`, insertError);
      return new Response(
        JSON.stringify({ success: false, error: 'Failed to create time block' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }

    console.log(`[${requestId}] Time block created`, timeBlock);

    return new Response(
      JSON.stringify({
        success: true,
        message: `Time block "${payload.title}" created successfully`,
        timeBlock,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    console.error(`[manage-time-blocks] Unhandled error`, err);
    return new Response(
      JSON.stringify({ success: false, error: 'An unexpected error occurred. Please try again.' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
